#-- Dependencies
markdown:         kramdown
kramdown:
  input:          GFM
  hard_wrap:      false
  toc_levels:     2..2
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  # use_coderay:    false
excerpt_separator: "<!--more-->"

#-- Permalinks
# permalink:            pretty
permalink:            /:categories/:title/

#-- Setup
title:            Hugo Ledoux
tagline:          'assistant-prof in <a href="https://3d.bk.tudelft.nl">3D geoinformation</a> at <a href="http://www.tudelft.nl">TU Delft</a>'
# description:      'yo'
url:              https://3d.bk.tudelft.nl
# baseurl:          ""
baseurl:          /hledoux

author:
  name:           'Hugo Ledoux'
  url:            https://twitter.com/hugoledoux

# paginate:         5


